<?php
return [
    1 => [
        1 => true,
        3 => false,
        4 => false,
        5 => false,
        6 => false,
        7 => false,
        8 => false,
        10 => true,
        11 => false,
        12 => false,
    ],
    2 => [
        1 => false,
        2 => false,
        3 => true,
        4 => true,
        5 => false,
        6 => false,
        7 => false,
        8 => false,
        9 => false,
        10 => false,
        12 => false,
        13 => true,
    ],
    3 => [ 
        1 => false,
        2 => false,
        3 => false,
        4 => false,
        5 => false,
        6 => true,
        7 => false,
        8 => false,
        9 => false,
        10 => false,
        11 => false,
        12 => false,
        13 => true,
    ],
    4 => [
        1 => false,
        2 => false,
        3 => false,
        4 => false,
        5 => false,
        6 => false,
        7 => false,
        8 => false,
        9 => true,
        10 => false,
        11 => true,
        12 => false,
    ],
    5 => [
        1 => true,
        2 => true,
        3 => false,
        4 => false,
        5 => false,
        6 => true,
        7 => false,
        8 => false,
        9 => false,
        10 => false,
        11 => false,
        12 => false
    ],
    6 => [ 
        1 => true,
        3 => false,
        4 => false,
        6 => true,
        7 => true,
        8 => false,
        11 => false,
        12 => false,
    ],
    7 => [
        1 => false,
        3 => false,
        4 => true,
        5 => false,
        6 => false,
        7 => false,
        8 => false,
        9 => true,
        10 => false,
        11 => false,
        12 => false,
    ],
    8 => [
        1 => false,
        2 => false,
        3 => false,
        4 => false,
        5 => true,
        7 => false,
        8 => false,
        9 => false,
        10 => false,
        11 => false,
        12 => false,
    ],
    9 => [
        1 => false,
        3 => false,
        4 => false,
        5 => false,
        6 => false, 
        8 => false,
        9 => true,
        12 => true,
    ],
    10 => [
        2 => true,
        3 => true,
        4 => true,
        5 => false,
        6 => false,
        7 => false,
        8 => true,
        9 => false,
        10 => false,
        12 => false,
    ],
    11 => [
        3 => false,
        4 => false,
        5 => false,
        6 => false,
        9 => true,
        11 => false,
        12 => true,
    ],
    12 => [
        1 => true,
        2 => true,
        3 => true,
        5 => false,
        6 => false,
        8 => false,
        10 => true,
        11 => false,
        12 => false,
        13 => true,
    ],
    13 => [
        3 => true,
        12 => true,
        13 => true,
    ],
    14 => [
        
    ],
];
?>